name = "know-your-meals-api"
main = "src/index.ts"
compatibility_date = "2026-07-02"
compatibility_flags = ["nodejs_compat"]

[vars]
IMAGES_BASE_URL = "https://pub-ec6f9e5e07a74dd4b273a9ba89e6ab93.r2.dev"

[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "know-your-meals-images"
